steps:
  - label: ":hammer: Terraform Deploy"
    commands:
    - pwd
    - mkdir -p ./tools
    - wget https://releases.hashicorp.com/terraform/"$$TERRAFORM_VERSION"/terraform_"$$TERRAFORM_VERSION"_linux_amd64.zip
    - unzip -o terraform_"$$TERRAFORM_VERSION"_linux_amd64.zip -d ./tools
    - chmod u+x ./tools/terraform
    - wget https://github.com/gruntwork-io/terragrunt/releases/download/v$$TERRAGRUNT_VERSION/terragrunt_linux_amd64
    - mv terragrunt_linux_amd64 ./tools/terragrunt
    - chmod u+x ./tools/terragrunt
    - export PATH=$$(pwd)/tools:$PATH
    - pwd
    - echo "Hello World!"
    - terraform --version
    - terragrunt --version
    ##################################################
    # Run Terragrunt                              ####
    ##################################################
    - echo "--- run terraform to deploy to burner account"
    - aws --version
    - aws sts get-caller-identity
    - cd config/dev
    - terragrunt run-all apply -auto-approve --terragrunt-non-interactive
    - buildkite-agent oidc request-token --audience sts.amazonaws.com
    env:
      TERRAFORM_VERSION: "1.3.4"
      TERRAGRUNT_VERSION: "0.40.0"
    plugins:
    - aws-assume-role-with-web-identity:
        role-arn: arn:aws:iam::973606771572:role/BuildkiteOIDC
