#!/bin/bash

set +u

echo "--- :terraform: Setting up Terragrunt build environment"

# TERRAFORM_VERSION=1.3.4
# TERRAGRUNT_VERSION=0.40.0

# if [ ! -f ./tools ]; then
#     mkdir -p ./tools
#     wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
#     unzip -o terraform_"$TERRAFORM_VERSION"_linux_amd64.zip -d ./tools
#     chmod u+x ./tools/terraform

#     wget https://github.com/gruntwork-io/terragrunt/releases/download/v$TERRAGRUNT_VERSION/terragrunt_linux_amd64
#     mv terragrunt_linux_amd64 ./tools/terragrunt
#     chmod u+x ./tools/terragrunt
# fi
